### ISSUE TITLE
Change "not" to "now"

### ISSUE THREAD

**Issue by laarchambault** [learn-co-curriculum/active-record-associations-and-migrations#3]
Near the bottom of the README, I think the paragraph below should read "now persisted" instead of "not".

We added rolling_in_the_deep to adele's collection of songs and we can see the adele knows it has that song in the collection and rolling_in_the_deep knows about its artist. Not only that, rolling_in_the_deep is not persisted to the database.

**Comment by laarchambault** [comment]
Also, the very next paragraph has a sentence that is a run-on. It needs a conjunction or transition.

"To add to that collection, we use the shovel operator, <<, to operate on that collection, ["and" needed, or begin new sentence] treat adele.songs like any other array."

**Comment by sylwiavargas** [comment]
Thank you for helping us keep Learn.co understandable. I've fixed the typos.
